### ISSUE TITLE
Inkscape recipe fails because there are no mac downloads for latest Inkscape

### ISSUE THREAD

**Issue by deltasquare4** [autopkg/hansen-m-recipes#102]
The Inkscape recipe takes the latest version (`0.92.3` at the moment), and attempts to download the latest DMG from `https://inkscape.org/en/release/0.92.3/mac-os-x/`. It fails because there are no downloads available there yet. Though `https://inkscape.org/en/release/0.92.2/mac-os-x/` has DMG download available.

**Comment by rustymyers** [comment]
Appears there is not a macOS release for 0.92.3, which breaks the download recipe because it looks for the latest version to download. 

> Note: A build of 0.92.3 is not currently available for MacOS. The project welcomes additional contributors with MacOS expertise.

So the recipe could be re-written in some way, but the Inkscape site doesn't have much hope for checking for the latest macOS version of the software specifically. We could also just wait for the next macOS version for Inkscape. If you need the recipe to be hardcoded to 0.92.2, you could fork it or create an override. Updating SEARCH_PATTERN1 to force `(Current stable version: )` and using `-k version=0.92.2` when running the recipe would allow it to work until a new version is published.

**Comment by rustymyers** [comment]
Closing for now, probably need a better way to scrape for the latest macOS version of Inkscape, but the recipe can continue to fail without any consequences until the version mismatch is resolved on the developers side.
