### ISSUE TITLE
DymoLabel.download doesn't function. 

### ISSUE THREAD

**Issue by Darks7ar** [autopkg/hansen-m-recipes#188]
Would recommend removing recipe. the recipe from @joshua-d-miller works.

**Comment by rustymyers** [comment]
Our recipes were intended to do a more automatic method of determining the current version. This is broken due to the changes Dymo put in place on their site. Curl now returns: 
```
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>


            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>```

I've tried with the user agent, but that doesn't help. Not sure how to accomplish this accurately, as other sites that claim to list the latest versions (LabelCity) are out of date.

I have fixed these recipes, but will look at removing them if we can't find a work around, in which case we will rename them (probably).

**Comment by rustymyers** [comment]
% /usr/bin/curl --url https://download.dymo.com/dymo/Software/Mac/DLS8Setup.8.7.5.dmg --fail --output /Volumes/T7/AutoPkg/Cache/local.bigfix.DymoLabel/downloads/tmpfpo0cmff
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403

 % /usr/bin/curl -O --url https://download.dymo.com/dymo/Software/Mac/DLS8Setup.8.7.5.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11903    0 11903    0     0  44916      0 --:--:-- --:--:-- --:--:-- 44916

**Comment by rustymyers** [comment]
Removed and pointing to com.github.joshua-d-miller.download.dymolabel
