### ISSUE TITLE
Problem with Win recipes from AutoPkgR

### ISSUE THREAD

**Issue by patgmac** [autopkg/hansen-m-recipes#39]
Lately, I've been getting an error whenever running your Win recipes from within AutoPkgR. 

Errno 2 No such file or directory. 

`Mar 14 09:47:14 col-pgalla2-11v AutoPkgr[91214]: Run status: Processing com.github.hansen-m.download.FirefoxESR-Win...
Mar 14 09:47:14 col-pgalla2-11v AutoPkgr[91214]: Processing com.github.hansen-m.download.FirefoxESR-Win...
Mar 14 09:47:15 col-pgalla2-11v AutoPkgr[91214]: Error [1] Error running recipes 
Mar 14 09:47:17 col-pgalla2-11v AutoPkgr[91214]: [DEBUG] Completed AutoPkg Task:
      /usr/bin/python /usr/local/bin/autopkg run com.github.hansen-m.download.FirefoxESR-Win --report-plist /var/folders/y2/zc31smvd50j8jtwqg14lj8kjrbxhc7/T/com.lindegroup.AutoPkgr/20160314094714 -v`

The same recipes run fine from the command line. I'm assuming this a a path issue somewhere?
I did update p7zip via brew and 7z is in /usr/local/bin.

**Comment by hansen-m** [comment]
Yep, I tried it and I'm seeing the same thing. I don't use AutoPkgr so I've never run into this. If you launch AutoPkgr via the Terminal it seems to inherit the path from the shell environment and does work. 

This feels like an issue that AutoPkgr needs to address. Likely by amending the path in their NSTask calls.

**Comment by jgstew** [comment]
@hansen-m Can you add details here: https://github.com/lindegroup/autopkgr/issues/510

**Comment by mpanighetti** [comment]
Mentioned this in [lindegroup/autopkgr#510](https://github.com/lindegroup/autopkgr/issues/510), but the issue is that AutoPkgr is using a `$PATH` definition that doesn't include `/usr/local/bin` (it only looks at `/usr/bin:/bin:/usr/sbin:/sbin`) when running `autopkg` commands, which is where 7-Zip is stored when installed by Homebrew.

Since AutoPkgr has not been updated in some time and that isn't expected to change any time soon, the fix would be to include the full binary path to 7-Zip (`/usr/local/bin/7z` when installed by Homebrew) and other third-party binaries in this and other processors which require them. I'll submit a PR to make the change, though I'm not sure if you want to standardize on Homebrew standards or write the processors to accept multiple possible paths.
